"""Initial migration

Revision ID: 0df3fc9ed11c
Revises:
Create Date: 2026-09-03 21:08:45.637352

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0df3fc9ed11c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_profiles',
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('autonomy_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('buyer_id')
    )
    op.create_index(op.f('ix_buyer_profiles_buyer_id'), 'buyer_profiles', ['buyer_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('merchant_version', sa.Integer(), nullable=False),
    sa.Column('buyer_cohort_version', sa.String(), nullable=False),
    sa.Column('chaos_profile', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=False)
    op.create_table('failure_clusters',
    sa.Column('failure_id', sa.String(), nullable=False),
    sa.Column('taxonomy', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=False),
    sa.Column('estimated_lost_value_paise', sa.Integer(), nullable=True),
    sa.Column('supporting_trace_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('failure_id')
    )
    op.create_index(op.f('ix_failure_clusters_failure_id'), 'failure_clusters', ['failure_id'], unique=False)
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active_twin_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_index(op.f('ix_merchants_merchant_id'), 'merchants', ['merchant_id'], unique=False)
    op.create_table('processed_webhook_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razorpay_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.create_table('buyer_intents',
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('raw_intent', sa.Text(), nullable=False),
    sa.Column('hard_constraints', sa.JSON(), nullable=True),
    sa.Column('soft_preferences', sa.JSON(), nullable=True),
    sa.Column('budget_paise', sa.Integer(), nullable=True),
    sa.Column('expected_valid_sku_set', sa.JSON(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.buyer_id'], ),
    sa.PrimaryKeyConstraint('intent_id')
    )
    op.create_index(op.f('ix_buyer_intents_intent_id'), 'buyer_intents', ['intent_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_experiment_runs_run_id'), 'experiment_runs', ['run_id'], unique=False)
    op.create_table('merchant_policies',
    sa.Column('policy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('policy_type', sa.String(), nullable=False),
    sa.Column('policy_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('merchant_twin_versions',
    sa.Column('version_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catalog_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('repair_proposals',
    sa.Column('repair_id', sa.String(), nullable=False),
    sa.Column('failure_id', sa.String(), nullable=False),
    sa.Column('repair_type', sa.String(), nullable=False),
    sa.Column('proposed_patch', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('estimated_repair_cost_paise', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('before_metrics', sa.JSON(), nullable=True),
    sa.Column('after_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['failure_id'], ['failure_clusters.failure_id'], ),
    sa.PrimaryKeyConstraint('repair_id')
    )
    op.create_index(op.f('ix_repair_proposals_repair_id'), 'repair_proposals', ['repair_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_inventory_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('pricing_snapshots',
    sa.Column('pricing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('cost_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_paise >= 0', name='chk_cost_non_negative'),
    sa.CheckConstraint('price_paise >= 0', name='chk_price_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('pricing_id')
    )
    op.create_table('product_attributes',
    sa.Column('attribute_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('attribute_id')
    )
    op.create_table('transaction_traces',
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('final_classification', sa.String(), nullable=True),
    sa.Column('final_amount_paise', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.buyer_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.run_id'], ),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_transaction_traces_trace_id'), 'transaction_traces', ['trace_id'], unique=False)
    op.create_table('chaos_injections',
    sa.Column('chaos_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('mutated_state', sa.JSON(), nullable=True),
    sa.Column('reversible_patch', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['transaction_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('chaos_id')
    )
    op.create_index(op.f('ix_chaos_injections_chaos_id'), 'chaos_injections', ['chaos_id'], unique=False)
    op.create_table('payment_operations',
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('razorpay_signature', sa.String(), nullable=True),
    sa.Column('payment_operation_fingerprint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_paise >= 0', name='chk_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['trace_id'], ['transaction_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('operation_id'),
    sa.UniqueConstraint('payment_operation_fingerprint')
    )
    op.create_index(op.f('ix_payment_operations_operation_id'), 'payment_operations', ['operation_id'], unique=False)
    op.create_table('replay_results',
    sa.Column('replay_id', sa.String(), nullable=False),
    sa.Column('repair_id', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metrics_diff', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repair_proposals.repair_id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['transaction_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('replay_id')
    )
    op.create_index(op.f('ix_replay_results_replay_id'), 'replay_results', ['replay_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['transaction_traces.trace_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trace_events')
    op.drop_index(op.f('ix_replay_results_replay_id'), table_name='replay_results')
    op.drop_table('replay_results')
    op.drop_index(op.f('ix_payment_operations_operation_id'), table_name='payment_operations')
    op.drop_table('payment_operations')
    op.drop_index(op.f('ix_chaos_injections_chaos_id'), table_name='chaos_injections')
    op.drop_table('chaos_injections')
    op.drop_index(op.f('ix_transaction_traces_trace_id'), table_name='transaction_traces')
    op.drop_table('transaction_traces')
    op.drop_table('product_attributes')
    op.drop_table('pricing_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_repair_proposals_repair_id'), table_name='repair_proposals')
    op.drop_table('repair_proposals')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    op.drop_table('merchant_twin_versions')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_experiment_runs_run_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_buyer_intents_intent_id'), table_name='buyer_intents')
    op.drop_table('buyer_intents')
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_merchants_merchant_id'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_failure_clusters_failure_id'), table_name='failure_clusters')
    op.drop_table('failure_clusters')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_buyer_profiles_buyer_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
